---
title: "analysis3"
output: html_document
date: "2024-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(readr)
library(tidyr)
library(corrplot)
```

```{r}
land_df = read_csv("TillableLand.csv") %>%
  rename(tillable = "Total Class 2a Tillable Acres")

crops_df = read_csv("crops.csv") %>%
  rename(
    corn_harvested = "CORN, GRAIN - ACRES HARVESTED",
    corn_produced = "CORN, GRAIN - PRODUCTION, MEASURED IN BU",
    corn_grain_per_acre = "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",
    soybeans_harvested = "SOYBEANS - ACRES HARVESTED", 
    soybeans_produced = "SOYBEANS - PRODUCTION, MEASURED IN BU",
    soybeans_grain_per_acre = "SOYBEANS - YIELD, MEASURED IN BU / ACRE") %>%
  select(Year, County, corn_harvested, corn_produced, corn_grain_per_acre, soybeans_harvested, soybeans_produced, soybeans_grain_per_acre) %>%
  mutate(
    across(where(is.numeric), ~replace_na(., 0))
  ) %>%
  mutate(
    soybeans_grain_per_acre = soybeans_grain_per_acre * 30.027682980816,
    corn_grain_per_acre = corn_grain_per_acre * 30.027682980816
  )

fertilizer_df = read_csv("FertilizerConsumption.csv") %>%
  rename(urea = "Urea (46-0-0)",
         potash = "Potash (0-0-60)",
         monammonium_phosphate = "Monammonium Phosphate (MAP) (11-52-0)",
         diammonium_phosphate = "Diammonium Phosphate (DAP) (18-46-0)",
         ammonia = "Ammonia (82-0-0)",
         district = "Ag District")
```

```{r}
fl_df <- inner_join(fertilizer_df, land_df, by = c("County", "Year")) %>%
  select(Year, County, district, urea, potash, monammonium_phosphate, diammonium_phosphate, ammonia, tillable)
flc_df <- inner_join(fl_df, crops_df, by = c("Year", "County")) %>%
  mutate(ammonia_per_acre = (ammonia/tillable)*907.1847,
         potash_per_acre = (potash/tillable)*907.1847,
         monammonium_phosphate_per_acre = (monammonium_phosphate/tillable)*907.1847,
         diammonium_phosphate_per_acre = (diammonium_phosphate/tillable)*907.1847,
         urea_per_acre = (urea/tillable)*907.1847)
```

```{r}
df1 <- flc_df %>%
  select(ammonia_per_acre, potash_per_acre, monammonium_phosphate_per_acre, diammonium_phosphate_per_acre, urea_per_acre, soybeans_grain_per_acre, corn_grain_per_acre)

corrplot(cor(df1), method = "color")
cor(df1)
```

```{r}

df2 <- flc_df %>%
  select(Year, County, ammonia_per_acre, potash_per_acre, monammonium_phosphate_per_acre, diammonium_phosphate_per_acre, urea_per_acre, soybeans_grain_per_acre, corn_grain_per_acre) %>%
  filter(County != "CARLTON") %>%
  rename(ammonia = ammonia_per_acre,
         potash = potash_per_acre,
         monammonium = monammonium_phosphate_per_acre,
         diammonium = diammonium_phosphate_per_acre,
         urea = urea_per_acre,
         soybeans = soybeans_grain_per_acre,
         corn = corn_grain_per_acre) %>%
  filter(Year == 2010) %>%
  select(-c(Year, County))

counties <- flc_df %>%
  filter(Year == 2010 & County != "CARLTON")

pca_result <- prcomp(df2, scale. = TRUE)

biplot(pca_result, col = c("gray", "black"), xpd = TRUE)
```
